#!/bin/bash
echo "  This script will create a user, and a directory for home assistant, then build the podman run command from that"
read -p "Any key to continue or ^C to exit"



###################
# All setup is here, modify for the container to set up
# Set variables to be used below
container_user="immich"
container_longname="immich"
# container_path=""

# Add the HA user if it doesn't exist 
useradd $container_user || echo "User already exists."



# create the user directory for the podman volume if it doesn't exist
dirName=/home/$container_user
if [ ! -d $dirName ];then
     if ! mkdir $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi

# Get the user and group ID for below
container_uid=`id -u $container_user`
container_gid=`id -g $container_user`


# If the home directory exists, set the ownership 
if [ ! -d $dirName ];then
     if ! chown -R $container_uid:$container_gid $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi

#podman-compose up


######  Leftover code from HA, replaced with a compose file for immich
#Now we have gathered the info start the container
#podman run -d \
#-p 8123:8123 \
##--name HomeAssistant  \
#-e PUID=1001 \
#-e PGID=1001 \
#-v /home/ha:/config:Z \
#-v /etc/localtime:/etc/localtime:ro \
#-v /media/music:/media:Z \
#--replace \
#--restart unless-stopped \
#--net=host \
#ghcr.io/home-assistant/home-assistant:latest
