#!/bin/bash
echo "  This script will create a user, and a directory for home assistant, then build the podman run command from that"
read -p "Any key to continue or ^C to exit"



###################
# All setup is here, modify for the container to set up
# Set variables to be used below
container_name="audiobookshelf"
container_user="audiobookshelf"
container_longname="audiobookshelf"
container_path="ghcr.io/advplyr/audiobookshelf"

# Add the HA user if it doesn't exist 
useradd $container_user || echo "User already exists."



# create the user directory for the podman volume if it doesn't exist
dirName=/home/$container_user
if [ ! -d $dirName ];then
     if ! mkdir $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi


# Get the user and group ID for below
container_uid=`id -u $container_user`
container_gid=`id -g $container_user`


# If the home directory exists, set the ownership 
if [ ! -d $dirName ];then
     if ! chown -R $container_uid:$container_gid $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi



# Now see if the container is running already

if [ "$(podman ps -q -f name=$container_name)" ]; then
    echo "Container $container_name is running, nothing to do"

else
# if the container isn't running, remove it and issue the run again
    echo "Container $container_name is not running."
    if [ "!$(podman container inspect $container_name > /dev/null 2>&1)" ]; then

        echo "$container_name is not running $(podman rm $container_name)"

    MediaDir="/media/audiobookshelf"
# start the container
    podman run -d  --restart=always \
    -e PUID=$container_id   \
    -e PGID=$container_grp   \
	-p 13378:80   \
	-v $MediaDir/config:/config:Z \
	-v $MediaDir/metadata:/metadata:Z   \
    -v $MediaDir/podcasts:/podcasts:Z \
	-v /media/Audiobooks:/audiobooks:Z \
	--name audiobookshelf \
	ghcr.io/advplyr/audiobookshelf

    fi
fi










