#!/bin/bash
echo "  This script will create a user, and a directory for home assistant, then build the podman run command from that"
read -p "Any key to continue or ^C to exit"



###################
# All setup is here, modify for the container to set up
# Set variables to be used below
container_user="heimdall"
container_longname="heimdall"
container_path="linuxserver/heimdall:latest"

# Add the HA user if it doesn't exist 
useradd $container_user || echo "User already exists."



# create the user directory for the podman volume if it doesn't exist
dirName=/home/$container_user
if [ ! -d $dirName ];then
     if ! mkdir $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi

# Get the user and group ID for below
container_uid=`id -u $container_user`
container_gid=`id -g $container_user`


# If the home directory exists, set the ownership 
if [ ! -d $dirName ];then
     if ! chown -R $container_uid:$container_gid $dirName; then  # Shorter version. Shell will complain if you p>
     echo "Can't make dir: $dirName"
     fi
fi


echo "To continue to start the container,"
read -p "Any key to continue or ^C to exit"

podman run -d \
  --name=heimdall \
  -e PUID=1010 \
  -e PGID=1010 \
  -e TZ=Etc/UTC \
  -p 8081:80 \
  -p 8443:443 \
  -v /home/heimdall/config:/config:Z \
  --restart unless-stopped \
  $container_path
