#!/bin/bash

# This is a template that only needs the variables at the top and the podman line at the bottom. 
# 
#
echo "  This script will create a user, and a directory for home assistant, then build the podman run command from that"
read -p "Any key to continue or ^C to exit"



###################
# All setup is here, modify for the container to set up
# Set variables to be used below
#####################
container_user="pinchflat"
container_longname="pinchflat"
container_path="ghcr.io/kieraneglin/pinchflat:latest"
########################


# Add the container user if it doesn't exist 
useradd $container_user || echo "User already exists."


# create the user directory for the podman volume if it doesn't exist
dirName=/home/$container_user
if [ ! -d $dirName ];then
     if ! mkdir $dirName; then 
     echo "Can't make dir: $dirName"
     fi
fi

# Get the user and group ID for below
container_uid=`id -u $container_user`
container_gid=`id -g $container_user`


# If the home directory exists, set the ownership 
if [ ! -d $dirName ];then
     if ! chown -R $container_uid:$container_gid $dirName; then  
     echo "Can't make dir: $dirName"
     fi
fi

# Be sure to replace /host/path/to/config and /host/path/to/downloads below with
# the paths to the directories you created in step 1
# Be sure to replace America/New_York with your local timezone
podman run -d \
  --name pinchflat \
  -e TZ=America/New_York \
   --user $(id -u pinchflat):$(id -g pinchflat) \
  -p 8945:8945 \
  -v $container_user:/config \
  -v $container_user:/downloads \
  ghcr.io/kieraneglin/pinchflat:latest
