#!/bin/bash
# Set up and run portainer to manage containers
# need to figure out running it as a user that's not root
#
podman volume create portainer_data

podman run  -d -p 8000:8000 -p 9443:9443 --name portainer --replace \
--privileged \
-v /run/podman/podman.sock:/run/podman/podman.sock:Z \
-v portainer_data:/data:Z \
docker.io/portainer/portainer-ce
